#!/usr/bin/env ruby

require "thor"
require "./generator"

require "./array_list"
require "./string_list"

class Generate < Thor
  desc "runner", "一括変換"
  option :range,   type: :string, aliases: "-r", default: nil,       desc: "範囲"
  option :target,  type: :string, aliases: "-t", default: "nightly", desc: "rustc の種類"
  option :method,  type: :string, aliases: "-m", default: nil,       desc: "対象メソッド"
  option :class,   type: :string, aliases: "-c", default: nil,       desc: "対象クラス"
  def runner
    list = [
      ARRAY_LIST,
      STRING_LIST,
    ]
    if v = options[:class]
      list = list.find_all { |e| e[:name].match?(v) }
    end
    new_options = options.transform_keys(&:to_sym)
    list.each do |e|
      Generator.new(e.merge(new_options)).run
    end
  end
end

Generate.start
