#!/usr/bin/env ruby

require "thor"
require "#{__dir__}/rust_wrapper"
require "#{__dir__}/embed_processor"

module RustXmpfilter
  class CLI < Thor
    default_command :runner

    desc "runner", "実行"
    option :overwrite, type: :boolean, aliases: "-w", default: false, desc: "ファイル上書き"
    def runner(*files)
      if File.pipe?(STDIN) || File.select([STDIN], [], [], 0)
        puts EmbedProcessor.new(options.merge(source_code: STDIN.read)).to_s
      else
        files.each do |e|
          e = Pathname(e)
          str = RustWrapper.new(options.merge(source_code: e.read)).to_s
          if options[:overwrite]
            e.write(str)
          else
            puts str
          end
        end
      end
    end
  end
end

RustXmpfilter::CLI.start
