#!/usr/bin/env ruby

require "thor"
require "./method_matrix"
require "./case_option"
require "./case_result"

class Generate < Thor
  default_command :runner

  desc "runner", "実行"
  option :max, type: :numeric, aliases: "-l", default: nil, desc: "各件数最大"
  def runner
    new_options = options.transform_keys(&:to_sym)
    out = []
    [
      CaseOption,
      CaseResult,
    ].each do |e|
      out << MethodMatrix.new(e.merge(new_options)).to_s
    end
    body = out.join("\n")
    # file_write(Pathname("~/src/zenn-content/articles/#{@params[:slug]}.md"))
    file = Pathname("_output.md")
    file.write(body)
    puts file
  end
end

Generate.start
